import {
  bwAskkollel,
  bwBackground,
  bwCharts,
  bwChidon,
  bwDailyquiz,
  bwEngCharts,
  bwFullreview,
  bwGalai,
  bwHalacha,
  bwInsights,
  bwMemberssite,
  bwMishna,
  bwNavigator,
  bwPodcast,
  bwPoint,
  bwQnA,
  bwRevach,
  bwTalmud,
  bwTosfos,
  bwYerushalmy,
  bwYosef,

  coAskkollel,
  coBackground,
  coCharts,
  coChidon,
  coDailyquiz,
  coEngCharts,
  coFullreview,
  coGalai,
  coHalacha,
  coInsights,
  coMemberssite,
  coMishna,
  coNavigator,
  coPodcast,
  coPoint,
  coQnA,
  coRevach,
  coTalmud,
  coTosfos,
  coYerushalmy,
  coYosef,
  
} from '../imgs/';

export default [
  {
    hoverImg: coMishna,
    img: bwMishna,
    title: 'Mishna',
    link: '/Mishna',
  },
  {
    hoverImg: coInsights,
    img: bwInsights,
    title: 'Insights',
    link: '/Insights',
  },
  {
    hoverImg: coBackground,
    img: bwBackground,
    title: 'Background',
    link: '/Background',
  },
  {
    hoverImg: coQnA,
    img: bwQnA,
    title: 'Review Q&A',
    link: '/ReviewQA',
  },
  {
    hoverImg: coFullreview,
    img: bwFullreview,
    title: 'Full Review',
    link: '/FullReview',
  },
  {
    hoverImg: coEngCharts,
    img: bwEngCharts,
    title: 'English Charts',
    link: '/EnglishCharts',
  },
  {
    hoverImg: coPoint,
    img: bwPoint,
    title: 'Point by Point',
    link: '/PointByPoint',
  },
  {
    hoverImg: coHalacha,
    img: bwHalacha,
    title: 'Halachah',
    link: '/Halacha',
    
  },
  {
    hoverImg: coDailyquiz,
    img: bwDailyquiz,
    title: 'Daily Quiz',
    link: '/DailyQuiz',
  },
  {
    hoverImg: coTosfos,
    img: bwTosfos,
    title: 'Tosfos',
    link: '/TosFos',
  },
  {
    hoverImg: coRevach,
    img: bwRevach,
    title: "Revach L'daf",
    link: '/RevachLDaf',
  },
  {
    hoverImg: coPodcast,
    img: bwPodcast,
    title: 'Podcasts',
    link: '/PodCasts',
  },
  {
    hoverImg: coYosef,
    img: bwYosef,
    title: 'יוסף דעת',
    link: '/יוסף דעת',
  },
  {
    hoverImg: coCharts,
    img: bwCharts,
    title: 'טבלאות',
    link: '/טבלאות',
  },
  {
    hoverImg: coGalai,
    img: bwGalai,
    title: 'גלי מסכתא',
    link: '/גלי מסכתא',
  },
  {
    hoverImg: coChidon,
    img: bwChidon,
    title: 'חידונים',
    link: '/חידונים',
  },
  {
    hoverImg: coYerushalmy,
    img: bwYerushalmy,
    title: 'Yerushalmi matchup',
    link: '/YerushalmiMatchup',
  },
  {
    hoverImg: coYerushalmy,
    img: bwYerushalmy,
    title: 'Yerushalmi Audio',
    link: '/YerushalmiAudio',
  },
  {
    hoverImg: coAskkollel,
    img: bwAskkollel,
    title: 'Our Replies',
    link: '/OurReplies',
  },
];
