import {
  bwAskkollel,
  bwBackground,
  bwCharts,
  bwChidon,
  bwDailyquiz,
  bwEngCharts,
  bwFullreview,
  bwGalai,
  bwHalacha,
  bwInsights,
  bwMemberssite,
  bwMishna,
  bwNavigator,
  bwPodcast,
  bwPoint,
  bwQnA,
  bwRevach,
  bwTalmud,
  bwTosfos,
  bwYerushalmy,
  bwYosef,

  coAskkollel,
  coBackground,
  coCharts,
  coChidon,
  coDailyquiz,
  coEngCharts,
  coFullreview,
  coGalai,
  coHalacha,
  coInsights,
  coMemberssite,
  coMishna,
  coNavigator,
  coPodcast,
  coPoint,
  coQnA,
  coRevach,
  coTalmud,
  coTosfos,
  coYerushalmy,
  coYosef,
  
} from '../imgs/';

export default [
  {
    hoverImg: coMishna,
    img: bwMishna,
    title: 'Mishna',
    link: '/mishna', // this should like to actual mishan page, not content
  },
  {
    hoverImg: coInsights,
    img: bwInsights,
    title: 'Insights',
    link: '/insites',
  },
  {
    hoverImg: coBackground,
    img: bwBackground,
    title: 'Background',
    link: '/backgrnd',
  },
  {
    hoverImg: coQnA,
    img: bwQnA,
    title: 'Review Q&A',
    link: '/reviewq',
  },
  {
    hoverImg: coFullreview,
    img: bwFullreview,
    title: 'Full Review',
    link: '/review',
  },
  {
    hoverImg: coEngCharts,
    img: bwEngCharts,
    title: 'English Charts',
    link: '/engCharts',
  },
  {
    hoverImg: coPoint,
    img: bwPoint,
    title: 'Point by Point',
    link: '/points',
  },
  {
    hoverImg: coHalacha,
    img: bwHalacha,
    title: 'Halachah',
    link: '/halachah',
    
  },
  {
    hoverImg: coDailyquiz,
    img: bwDailyquiz,
    title: 'Daily Quiz',
    link: '/quiz',
  },
  {
    hoverImg: coTosfos,
    img: bwTosfos,
    title: 'Tosfos',
    link: '/tosfos',
  },
  {
    hoverImg: coRevach,
    img: bwRevach,
    title: "Revach L'daf",
    link: '/RevachLDaf',
  },
  {
    hoverImg: coPodcast,
    img: bwPodcast,
    title: 'Podcasts',
    link: '/PodCasts', // different
  },
  {
    hoverImg: coYosef,
    img: bwYosef,
    title: 'יוסף דעת',
    link: '/yosefdas',
  },
  {
    hoverImg: coCharts,
    img: bwCharts,
    title: 'טבלאות',
    link: '/hebcharts',
  },
  {
    hoverImg: coGalai,
    img: bwGalai,
    title: 'גלי מסכתא',
    link: '/galei',
  },
  {
    hoverImg: coChidon,
    img: bwChidon,
    title: 'חידונים',
    link: '/chidon',
  },
  {
    hoverImg: coYerushalmy,
    img: bwYerushalmy,
    title: 'Yerushalmi matchup',
    link: '/yerushalmi',
  },
  {
    hoverImg: coYerushalmy,
    img: bwYerushalmy,
    title: 'Yerushalmi Audio',
    link: '/yeraudio',
  },
  {
    hoverImg: coAskkollel,
    img: bwAskkollel,
    title: 'Our Replies',
    link: '/discuss',
  },
];
